[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
group = "git-dir"

[[plugin.prepend_previewers]]
id = "md"
url = "*.md"
run = "glow"
group = "md"
