# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  host-secrets,
  ...
}:
let
  cfg = config.miniluz.selfhosting;

  serverStorage = config.miniluz.selfhosting.server.serverStorage;
  dataDir = "${serverStorage}/librechat";

  librechat-env = config.age.secrets.librechat-env.path;
in
{
  options.miniluz.selfhosting.librechat = lib.mkEnableOption "Enable LibreChat";

  config = lib.mkIf (cfg.enable && cfg.librechat && cfg.server.enable) {

    age.secrets.librechat-env.file = "${host-secrets}/librechat-env.age";

    miniluz.selfhosting.backups.backups.librechat =
      let
        extractionPath = "/tmp/librechat-backup";
      in
      {
        paths = [ extractionPath ];
        preHook = ''
          export PATH=${lib.makeBinPath [ pkgs.podman ]}:$PATH

          echo "Creating backup directory"
          mkdir -p ${extractionPath}

          echo "Dumping MongoDB (LibreChat)"
          podman exec chat-mongodb mongodump --archive --gzip --db LibreChat \
            > ${extractionPath}/LibreChat-mongodb.gz

          echo "Dumping PostgreSQL (vectordb)"
          podman exec vectordb /bin/bash -c \
            'PGPASSWORD=$POSTGRES_PASSWORD pg_dump --username $POSTGRES_USER $POSTGRES_DB' \
            > ${extractionPath}/vectordb.sql
        '';
        postHook = ''
          echo "Cleaning up backup directory"
          rm -rf ${extractionPath}
        '';
      };

    systemd.tmpfiles.rules = [
      "d ${dataDir}/images            0750 root root"
      "d ${dataDir}/logs              0750 root root"
      "d ${dataDir}/uploads           0750 root root"
      "d ${dataDir}/meili_data_v1.35.1 0750 root root"
      "d ${dataDir}/data-node         0750 root root"
    ];

    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
      let
        matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
      in
      {
        "${matchAll}".allowedUDPPorts = [ 53 ];
      };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."LibreChat" = {
      image = "registry.librechat.ai/danny-avila/librechat-dev:latest";
      environment = {
        "HOST" = "0.0.0.0";
        "MEILI_HOST" = "http://meilisearch:7700";
        "MONGO_URI" = "mongodb://mongodb:27017/LibreChat";
        "RAG_API_URL" = "http://rag_api:8000";
        "RAG_PORT" = "8000";
      };
      environmentFiles = [
        librechat-env
      ];
      volumes = [
        "${dataDir}/images:/app/client/public/images:rw"
        "${dataDir}/logs:/app/logs:rw"
        "${dataDir}/uploads:/app/uploads:rw"
        "${./librechat.yaml}:/app/librechat.yaml:ro"
      ];
      ports = [
        "3080:3080/tcp"
      ];
      dependsOn = [
        "chat-mongodb"
        "rag_api"
      ];
      user = "0:0";
      log-driver = "journald";
      extraOptions = [
        "--add-host=host.docker.internal:host-gateway"
        "--network-alias=api"
        "--network=librechat_default"
      ];
    };
    systemd.services."podman-LibreChat" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-librechat_default.service"
      ];
      requires = [
        "podman-network-librechat_default.service"
      ];
      partOf = [
        "podman-compose-librechat-root.target"
      ];
      wantedBy = [
        "podman-compose-librechat-root.target"
      ];
    };
    virtualisation.oci-containers.containers."chat-meilisearch" = {
      image = "getmeili/meilisearch:v1.35.1";
      environment = {
        "MEILI_HOST" = "http://meilisearch:7700";
        "MEILI_NO_ANALYTICS" = "true";
      };
      environmentFiles = [
        librechat-env
      ];
      volumes = [
        "${dataDir}/meili_data_v1.35.1:/meili_data:rw"
      ];
      # user = ":";
      log-driver = "journald";
      extraOptions = [
        "--network-alias=meilisearch"
        "--network=librechat_default"
      ];
    };
    systemd.services."podman-chat-meilisearch" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-librechat_default.service"
      ];
      requires = [
        "podman-network-librechat_default.service"
      ];
      partOf = [
        "podman-compose-librechat-root.target"
      ];
      wantedBy = [
        "podman-compose-librechat-root.target"
      ];
    };
    virtualisation.oci-containers.containers."chat-mongodb" = {
      image = "mongo:8.0.20";
      environmentFiles = [
        librechat-env
      ];
      volumes = [
        "${dataDir}/data-node:/data/db:rw"
      ];
      cmd = [
        "mongod"
        "--noauth"
      ];
      # user = ":";
      log-driver = "journald";
      extraOptions = [
        "--network-alias=mongodb"
        "--network=librechat_default"
      ];
    };
    systemd.services."podman-chat-mongodb" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-librechat_default.service"
      ];
      requires = [
        "podman-network-librechat_default.service"
      ];
      partOf = [
        "podman-compose-librechat-root.target"
      ];
      wantedBy = [
        "podman-compose-librechat-root.target"
      ];
    };
    virtualisation.oci-containers.containers."rag_api" = {
      image = "registry.librechat.ai/danny-avila/librechat-rag-api-dev-lite:latest";
      environment = {
        "DB_HOST" = "vectordb";
        "RAG_PORT" = "8000";
      };
      environmentFiles = [
        librechat-env
      ];
      dependsOn = [
        "vectordb"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=rag_api"
        "--network=librechat_default"
      ];
    };
    systemd.services."podman-rag_api" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-librechat_default.service"
      ];
      requires = [
        "podman-network-librechat_default.service"
      ];
      partOf = [
        "podman-compose-librechat-root.target"
      ];
      wantedBy = [
        "podman-compose-librechat-root.target"
      ];
    };
    virtualisation.oci-containers.containers."vectordb" = {
      image = "pgvector/pgvector:0.8.0-pg15-trixie";
      environmentFiles = [
        librechat-env
      ];
      volumes = [
        "librechat_pgdata2:/var/lib/postgresql/data:rw"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=vectordb"
        "--network=librechat_default"
      ];
    };
    systemd.services."podman-vectordb" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-librechat_default.service"
        "podman-volume-librechat_pgdata2.service"
      ];
      requires = [
        "podman-network-librechat_default.service"
        "podman-volume-librechat_pgdata2.service"
      ];
      partOf = [
        "podman-compose-librechat-root.target"
      ];
      wantedBy = [
        "podman-compose-librechat-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-librechat_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f librechat_default";
      };
      script = ''
        podman network inspect librechat_default || podman network create librechat_default
      '';
      partOf = [ "podman-compose-librechat-root.target" ];
      wantedBy = [ "podman-compose-librechat-root.target" ];
    };

    # Volumes
    systemd.services."podman-volume-librechat_pgdata2" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        podman volume inspect librechat_pgdata2 || podman volume create librechat_pgdata2
      '';
      partOf = [ "podman-compose-librechat-root.target" ];
      wantedBy = [ "podman-compose-librechat-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-librechat-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
