# This file was generated by 'luznix-generate-miniluz-pkgs'.
attrs: {
  luznix-generate-import-all = import ./nix-helpers/luznix-generate-import-all.nix attrs;
  luznix-rebuild = import ./nix-helpers/luznix-rebuild.nix attrs;
  luznix-generate-miniluz-pkgs = import ./nix-helpers/luznix-generate-miniluz-pkgs.nix attrs;
  luznix-shell-setup = import ./nix-helpers/luznix-shell-setup.nix attrs;
  writeNuApplication = import ./nix-helpers/writeNuApplication.nix attrs;
  luznix-generate-hosts = import ./nix-helpers/luznix-generate-hosts.nix attrs;
  neovim = import ./neovim.nix attrs;
  code-windsurf = import ./scripts/code-windsurf.nix attrs;
  font-cache-update = import ./scripts/font-cache-update.nix attrs;
  bg-run = import ./scripts/bg-run.nix attrs;
  code-nw = import ./scripts/code-nw.nix attrs;
  git-clean-branches = import ./scripts/git-clean-branches.nix attrs;
}
