# This file was generated by 'generate-import-all'.
{
  imports = [
    ./probe-rs-rules.nix
    ./nix_configuration.nix
    ./obs.nix
    ./s3fs.nix
    ./tailscale.nix
    ./podman.nix
    ./steam.nix
    ./gaming/playit.nix
    ./base_configuration.nix
    ./amdgpu.nix
    ./gnome.nix
    ./virt.nix
  ];
}
